import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ReactFlow, Background, Controls, Position, type Node, type Edge } from '@xyflow/react';
import { Shield, Folder, Activity, Workflow, Settings, Users, Sun, Moon, LogOut, Plus, ArrowUpRight, Download, Play, Upload, ChevronRight, Search, Clock, Database, Radio, Check, X } from 'lucide-react';
import '@xyflow/react/dist/style.css';
import './style.css';

type Obj = Record<string, any>;
let csrf = '';
async function api(path: string, method='GET', body?: unknown): Promise<any> {
  const form = body instanceof FormData;
  const response = await fetch('/api/v1'+path, {method, credentials:'same-origin', headers:{...(form ? {} : {'Content-Type':'application/json'}), 'X-CSRF-Token':csrf}, body: body === undefined ? undefined : form ? body : JSON.stringify(body)});
  if (!response.ok) { const error = await response.json().catch(()=>({detail:response.statusText})); throw new Error(typeof error.detail === 'string' ? error.detail : JSON.stringify(error.detail)); }
  return response.json();
}
const when = (value: string) => value ? new Date(value).toLocaleString() : '—';
const inZone = (value: string, zone: string) => {try{return new Date(value).toLocaleString(undefined,{timeZone:zone})}catch{return when(value)}};
const bytes = (value: number) => value ? (value/1024**3).toFixed(1)+' GB' : '—';
function Badge({state}:{state:string}) {return <span className={'badge '+state}><i/>{state?.replaceAll('_',' ') || 'not run'}</span>}
function Empty({title,detail}:{title:string,detail:string}) {return <div className="empty"><Folder size={30}/><h3>{title}</h3><p>{detail}</p></div>}
function Field({label,children}:{label:string,children:React.ReactNode}) {return <label className="field"><span>{label}</span>{children}</label>}

function App() {
  const [user,setUser] = useState<Obj|null>(null), [loading,setLoading]=useState(true), [page,setPage]=useState('projects'), [selected,setSelected]=useState<string|null>(null);
  const [error,setError]=useState(''), [notice,setNotice]=useState(''), [theme,setTheme]=useState(localStorage.getItem('cvex-theme')||'dark');
  const [projects,setProjects]=useState<Obj[]>([]), [project,setProject]=useState<Obj|null>(null), [search,setSearch]=useState(''), [create,setCreate]=useState(false);
  const [status,setStatus]=useState<Obj|null>(null), [connected,setConnected]=useState(false), [settingsTarget,setSettingsTarget]=useState('nvd');
  const [activity,setActivity]=useState<Obj[]>([]), [users,setUsers]=useState<Obj[]>([]), [busy,setBusy]=useState(false);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('cvex-theme',theme)},[theme]);
  useEffect(()=>{api('/auth/me').then(u=>{csrf=u.csrf;setUser(u)}).catch(()=>{}).finally(()=>setLoading(false))},[]);
  const refresh=async()=>{setProjects(await api('/projects'));if(selected)setProject(await api('/projects/'+selected));};
  useEffect(()=>{if(!user)return;refresh().catch(e=>setError(e.message));const id=setInterval(()=>refresh().catch(()=>{}),5000);return()=>clearInterval(id)},[user,selected]);
  useEffect(()=>{if(!user||user.role!=='admin')return;
    const events=new EventSource('/api/v1/admin/events'); events.onmessage=e=>{setStatus(JSON.parse(e.data));setConnected(true)};events.onerror=()=>setConnected(false);
    const id=setInterval(()=>api('/admin/status').then(setStatus).catch(()=>{}),10000);
    api('/admin/status').then(setStatus).catch(()=>{});return()=>{events.close();clearInterval(id)};
  },[user]);
  useEffect(()=>{if(!user)return;if(page==='activity')api('/activity').then(setActivity).catch(e=>setError(e.message));if(page==='users')api('/users').then(setUsers).catch(e=>setError(e.message))},[page,user]);
  const act=async(action:()=>Promise<any>,message='Saved')=>{setError('');setBusy(true);try{await action();setNotice(message);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
  const openSettings=(target:string)=>{setSettingsTarget(target);setPage('settings')};
  if(loading)return <div className="splash"><Shield/>Loading workspace…</div>;
  if(!user)return <div className="login-layout"><div className="login-story"><div className="brand"><Shield/> CVEX<span>WORKSPACE</span></div><div><span className="eyebrow">CONTINUOUS VULNERABILITY INTELLIGENCE</span><h1>Know what changed.<br/><em>Know what matters.</em></h1><p>Your software inventory, current vulnerability intelligence, and the reports that connect them.</p><div className="login-line"><span>CVE List</span><span>→</span><Database/><span>←</span><span>NVD</span></div></div><small>One workspace. A clearer picture.</small></div><form className="login-card" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const u=await api('/auth/login','POST',Object.fromEntries(f));csrf=u.csrf;setUser(u);setError('')}catch(e){setError((e as Error).message)}}}><span className="eyebrow">WELCOME BACK</span><h2>Sign in to CVEX</h2><p>Use your internal team account.</p><Field label="Username"><input name="username" autoComplete="username" required/></Field><Field label="Password"><input name="password" type="password" autoComplete="current-password" required/></Field>{error&&<div className="alert">{error}</div>}<button className="primary">Sign in <ArrowUpRight size={16}/></button><small>Accounts are provisioned by your administrator.</small></form></div>;
  const nav=[['projects',Folder,'Projects'],['activity',Activity,'Activity'],...(user.role==='admin' ? [['architecture',Workflow,'Architecture'],['settings',Settings,'Settings'],['users',Users,'Team']] : [])] as const;
  const enabledSchedules=projects.filter(p=>p.schedule_enabled).length;
  return <div className="shell"><aside className="sidebar"><div className="brand"><Shield/> CVEX<span>WORKSPACE</span></div><div className="workspace-label">OPERATIONS / INTERNAL</div><nav>{nav.map(([key,Icon,label])=><button key={String(key)} className={page===key?'active':''} onClick={()=>{setPage(String(key));setError('')}}><Icon size={18}/>{String(label)}{key==='projects'&&<span className="nav-count">{projects.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="subtle-card"><Radio size={16}/><span>Local intelligence<br/><small>NVD + CVE List</small></span></div><button onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>} {theme==='dark'?'Light':'Dark'} appearance</button><div className="account"><div className="avatar">{user.username[0].toUpperCase()}</div><span>{user.username}<small>{user.role}</small></span><button aria-label="Change password" onClick={()=>setPage('account')}><Settings size={16}/></button><button aria-label="Sign out" onClick={()=>act(async()=>{await api('/auth/logout','POST');setUser(null)},'Signed out')}><LogOut size={16}/></button></div></div></aside>
  <main><header className="topbar"><span>Workspace <ChevronRight size={13}/> {page==='projects'&&selected?'Project details':page[0].toUpperCase()+page.slice(1)}</span><div><span className="environment">STAGING</span><Clock size={14}/>{new Date().toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</div></header>
  <div className="content">{error&&<div role="alert" className="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="notice"><Check size={16}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
  {page==='projects'&&!selected&&<><div className="page-heading"><div><span className="eyebrow">YOUR SOFTWARE, IN FOCUS</span><h1>Projects<span className="heading-dot">.</span></h1><p>A living view of your software inventory and vulnerability reports.</p></div><button className="primary" onClick={()=>setCreate(true)}><Plus size={17}/>New project</button></div><div className="stats"><Stat title="PROJECTS" value={projects.length} detail="Company workspaces"/><Stat title="SCHEDULED" value={enabledSchedules} detail="Automatic scan → report"/><Stat title="REPORT RETENTION" value="30" detail="Successful reports per project"/></div><div className="section-bar"><h2>Project directory</h2><div className="search"><Search size={16}/><input aria-label="Search projects" placeholder="Search company or project…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="project-grid">{projects.filter(p=>(p.company+' '+p.name).toLowerCase().includes(search.toLowerCase())).map(p=><button className="project-card" key={p.id} onClick={()=>setSelected(p.id)}><div className="card-top"><div className="folder-icon"><Folder size={23}/></div><ArrowUpRight size={18}/></div><small>{p.company}</small><h2>{p.name}</h2><p>{p.filename||'Upload your first SBOM to get started'}</p><div className="card-meta"><Badge state={p.latest_state||'ready'}/><span>{p.active_version||'No active version'}</span></div><footer><Clock size={13}/>{p.schedule_enabled?'Next '+when(p.next_run):'Manual scans · schedule disabled'}</footer></button>)}</div>{projects.length===0&&<Empty title="Your first project starts here" detail="Create a company workspace, upload an SBOM, and generate your first findings report."/>}</>}
  {page==='projects'&&selected&&project&&<><button className="back" onClick={()=>{setSelected(null);setProject(null)}}>← All projects</button><div className="page-heading"><div><span className="eyebrow">PROJECT WORKSPACE</span><h1>{project.company} <span className="muted">—</span> {project.name}</h1><p>Versioned software inventory. Reports built from current local intelligence.</p></div><div className="button-row">{user.role==='admin'&&<button onClick={()=>openSettings('project:'+selected)}><Clock size={16}/>Schedule</button>}<button className="primary" disabled={busy||!project.active_version_id} onClick={()=>act(()=>api('/projects/'+selected+'/runs','POST'),'Report job queued')}><Play size={16}/>Run now</button></div></div>
  <div className="inventory"><div><span className="eyebrow">SBOM VERSIONS</span><h3>Your report’s source of truth</h3><p>New runs use the active version. Historical reports keep their original version.</p></div><form className="upload-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const label=String(f.get('label')||'');f.delete('label');act(()=>api('/projects/'+selected+'/versions?label='+encodeURIComponent(label),'POST',f),'SBOM uploaded')}}><input aria-label="Version label" name="label" placeholder="Version label, e.g. 2.4.0" required/><input aria-label="SPDX JSON file" name="file" type="file" accept=".json,application/json" required/><button disabled={busy}><Upload size={16}/>Upload SPDX JSON</button></form></div>
  <div className="versions">{project.versions.map((v:Obj)=><div key={v.id}><div><strong>{v.label}</strong><small>{v.filename} · {when(v.created_at)}</small></div>{v.id===project.active_version_id?<Badge state="active"/>:<button disabled={busy} onClick={()=>act(()=>api(`/projects/${selected}/versions/${v.id}/activate`,'POST'),'Active version updated')}>Make active</button>}</div>)}</div>
  <div className="section-bar"><h2>Recent scans <span className="count">{project.jobs.length}</span></h2><small>Newest 30 successful reports retained</small></div><div className="table-wrap"><table><thead><tr><th>SCAN TIME</th><th>SBOM VERSION</th><th>STATUS</th><th>FINDINGS</th><th>REPORT</th></tr></thead><tbody>{project.jobs.map((j:Obj)=><tr key={j.id}><td><strong>{when(j.created_at)}</strong><small>{j.trigger}{j.finished_at&&j.started_at?' · '+Math.round((new Date(j.finished_at).getTime()-new Date(j.started_at).getTime())/1000)+'s':''}{j.scheduled_at?' · due '+when(j.scheduled_at):''}</small></td><td>{j.version_label}</td><td><Badge state={j.state}/>{j.total&&j.state==='scanning'?<small>{j.progress} / {j.total} components</small>:null}{j.error&&<small className="danger">{j.error}</small>}</td><td><Severity summary={j.summary}/></td><td>{j.state==='succeeded'?<div className="report-actions"><a href={`/api/v1/runs/${j.id}/artifacts/html`} target="_blank" rel="noopener noreferrer"><ArrowUpRight size={15}/>View HTML</a><a aria-label="Download HTML" href={`/api/v1/runs/${j.id}/artifacts/html?download=true`}><Download size={15}/></a><a href={`/api/v1/runs/${j.id}/artifacts/csv?download=true`}>CSV</a><a href={`/api/v1/runs/${j.id}/artifacts/json?download=true`}>JSON</a></div>:<span className="muted">Available after export</span>}</td></tr>)}</tbody></table>{!project.jobs.length&&<Empty title="No scans yet" detail="Run a scan now, or ask an admin to set a recurring schedule."/>}</div></>}
  {page==='architecture'&&<><div className="page-heading"><div><span className="eyebrow">SYSTEM OBSERVABILITY</span><h1>Architecture<span className="heading-dot">.</span></h1><p>Two independent workflows. One shared intelligence database.</p></div><Badge state={connected?'live':'reconnecting'}/></div><div className="stats"><Stat title="DATABASE" value={bytes(status?.database_bytes)} detail="Compact source intelligence"/><Stat title="REPORT QUEUE" value={status?.queue?.filter((q:Obj)=>q.state==='queued').reduce((n:number,q:Obj)=>n+Number(q.count),0)||0} detail="Awaiting report executor"/><Stat title="REPORT STORAGE" value={bytes(status?.workers?.find((w:Obj)=>w.name==='storage')?.details?.report_bytes)} detail="Retained project artifacts"/><Stat title="DISK AVAILABLE" value={bytes(status?.disk_free_bytes)} detail={'of '+bytes(status?.disk_total_bytes)}/></div><Architecture status={status} onSelect={openSettings}/><div className="section-bar"><h2>Report queue</h2><small>One active job per project</small></div><div className="table-wrap"><table><thead><tr><th>PROJECT</th><th>STATE</th><th>QUEUED AT</th><th>PROGRESS</th></tr></thead><tbody>{status?.jobs?.map((j:Obj)=><tr key={j.id}><td>{j.company} — {j.name}</td><td><Badge state={j.state}/></td><td>{when(j.created_at)}</td><td>{j.total?`${j.progress} / ${j.total} components`:'Waiting'}</td></tr>)}</tbody></table>{!status?.jobs?.length&&<Empty title="Queue is clear" detail="Scheduled and manual reports will appear here."/>}</div><div className="section-bar"><h2>Worker activity</h2><small>Measured heartbeats · updated every 3 seconds</small></div><div className="worker-grid">{status?.workers?.map((w:Obj)=><button className="worker-card" key={w.name} onClick={()=>openSettings(w.name)}><div><h3>{w.name}</h3><Badge state={w.stale?'stale':w.state}/></div><p>{w.phase||w.details?.phase||'Waiting'}</p><small>Heartbeat {when(w.heartbeat_at)}</small>{w.details?.processed!==undefined&&<small>{w.details.processed.toLocaleString()} processed · {w.details.changed??0} changed</small>}<small>Applied settings v{w.applied_version??'—'}</small>{status.sources?.filter((s:Obj)=>s.source===w.name).map((s:Obj)=><div className="source-details" key={s.source}><small>Last success {when(s.last_success)}</small><small>Next run {when(status.schedules?.find((x:Obj)=>x.target===w.name)?.next_run)}</small>{s.error_count>0&&<small className="warning">{s.error_type||'Synchronization error'} · {s.error_count} failures · retry {when(s.next_retry_at)}</small>}</div>)}</button>)}</div></>}
  {page==='account'&&<div className="panel"><h2>Change your password</h2><p>All sessions will be signed out after changing your password.</p><form onSubmit={e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));act(async()=>{await api('/auth/password','POST',body);setUser(null)},'Password changed. Sign in again.')}}><Field label="Current password"><input name="current_password" type="password" autoComplete="current-password" required/></Field><Field label="New password"><input name="new_password" type="password" minLength={12} autoComplete="new-password" required/></Field><button className="primary" disabled={busy}>Change password</button></form></div>}
  {page==='settings'&&<SettingsPanel target={settingsTarget} projects={projects} onSelect={setSettingsTarget} act={act} busy={busy}/>}
  {page==='activity'&&<><div className="page-heading"><div><span className="eyebrow">WORKSPACE JOURNAL</span><h1>Activity<span className="heading-dot">.</span></h1><p>Account, project, report, and configuration events.</p></div></div><div className="table-wrap"><table><thead><tr><th>TIME</th><th>ACTOR</th><th>EVENT</th><th>DETAILS</th></tr></thead><tbody>{activity.map(a=><tr key={a.id}><td>{when(a.created_at)}</td><td>{a.actor}</td><td>{a.action.replaceAll('_',' ')}</td><td><code>{JSON.stringify(a.details)}</code></td></tr>)}</tbody></table></div></>}
  {page==='users'&&<><div className="page-heading"><div><span className="eyebrow">INTERNAL ACCESS</span><h1>Team<span className="heading-dot">.</span></h1><p>All team members share project access. Administrators manage system settings.</p></div></div><div className="inventory"><form className="inline-form" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));act(async()=>{await api('/users','POST',f);setUsers(await api('/users'))},'Account created')}}><Field label="Username"><input name="username" required/></Field><Field label="Password · 12+ characters"><input name="password" type="password" minLength={12} required/></Field><Field label="Role"><select name="role"><option value="user">User</option><option value="admin">Administrator</option></select></Field><button className="primary" disabled={busy}>Create account</button></form></div><div className="table-wrap"><table><thead><tr><th>USERNAME</th><th>ROLE</th><th>CREATED</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td><Badge state={u.role}/></td><td>{when(u.created_at)}</td></tr>)}</tbody></table></div></>}
  <footer className="page-footer"><span><Shield size={13}/> CVEX / SOFTWARE INTELLIGENCE</span><span>Current data. Traceable reports.</span></footer></div></main>
  {create&&<div className="modal-backdrop"><form className="modal" onSubmit={e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));act(async()=>{const p=await api('/projects','POST',body);setCreate(false);setSelected(p.id)},'Project created')}}><button type="button" className="close" aria-label="Close" onClick={()=>setCreate(false)}><X size={18}/></button><div className="folder-icon"><Folder/></div><h2>Create a project</h2><p>A dedicated home for your SBOM versions and reports.</p><Field label="Company"><input name="company" placeholder="Company name" required maxLength={200}/></Field><Field label="Project / SBOM name"><input name="name" placeholder="e.g. Spot Pro firmware" required maxLength={200}/></Field><button className="primary" disabled={busy}>Create project <ChevronRight size={16}/></button></form></div>}</div>
}

function Stat({title,value,detail}:{title:string,value:any,detail:string}) {return <div className="stat"><small>{title}</small><strong>{value}</strong><span>{detail}</span></div>}
function Severity({summary}:{summary:Obj}) {if(!summary)return <span className="muted">—</span>;const counts=summary.counts?.severity||{};const stale=Object.values(summary.source_freshness||{}).some((s:any)=>['stale','failed','degraded'].includes(s?.health));return <><div className="severity">{Object.keys(counts).length?Object.entries(counts).map(([k,v])=><span key={k} className={k.toLowerCase()} title={k}>{String(v)} {k}</span>):<span>No findings</span>}</div>{stale&&<small className="warning">Source freshness warning</small>}</>}

function Architecture({status,onSelect}:{status:Obj|null,onSelect:(s:string)=>void}) {
  const worker=(name:string)=>status?.workers?.find((w:Obj)=>w.name===name);
  const active=(name:string)=>['running','scanning','exporting'].includes(worker(name)?.state)&&!worker(name)?.stale;
  const specs=[['cve-upstream','CVE List repository',0,0],['nvd-upstream','NVD API',0,150],['cve','CVE synchronization',270,0],['nvd','NVD synchronization',270,150],['database','PostgreSQL intelligence',540,75],['scheduler','Project schedules',0,360],['queue','Report job queue',270,360],['report-worker','Scan → export',540,360],['storage','Project reports',810,360]];
  const nodes:Node[]=specs.map(([id,label,x,y])=>({id:String(id),position:{x:Number(x),y:Number(y)},sourcePosition:Position.Right,targetPosition:Position.Left,data:{label:<div><small>{String(id).includes('upstream')?'UPSTREAM':worker(String(id))?.stale?'STALE':worker(String(id))?.state?.toUpperCase()||'MODULE'}</small><strong>{label}</strong></div>},className:active(String(id))?'node-active':''}));
  const links=[['cve-upstream','cve','cve'],['nvd-upstream','nvd','nvd'],['cve','database','cve'],['nvd','database','nvd'],['scheduler','queue','scheduler'],['queue','report-worker','report-worker'],['database','report-worker','report-worker'],['report-worker','storage','report-worker']];
  const edges:Edge[]=links.map(([source,target,name])=>({id:source+target,source,target,animated:active(name),style:{stroke:active(name)?'#59dfcb':'#52606d'},type:'smoothstep'}));
  return <div className="architecture"><div className="diagram-caption"><span>SOURCE SYNCHRONIZATION</span><small>Click a module to inspect its settings</small></div><ReactFlow nodes={nodes} edges={edges} fitView nodesDraggable={false} nodesConnectable={false} onNodeClick={(_,n)=>onSelect(n.id.replace('-upstream',''))} colorMode={document.documentElement.dataset.theme==='light'?'light':'dark'}><Background color="#35404b" gap={24}/><Controls showInteractive={false}/></ReactFlow><div className="diagram-bottom">PROJECT REPORTING <span>Independent schedules · shared local data</span></div></div>
}

function SettingsPanel({target,projects,onSelect,act,busy}:{target:string,projects:Obj[],onSelect:(s:string)=>void,act:(f:()=>Promise<any>,m?:string)=>Promise<void>,busy:boolean}) {
  const [schedule,setSchedule]=useState<Obj|null>(null),[settings,setSettings]=useState<Obj|null>(null),[error,setError]=useState('');
  const source=['nvd','cve'].includes(target), schedulable=source||target.startsWith('project:');
  useEffect(()=>{setSchedule(null);setSettings(null);setError('');if(schedulable)api('/schedules/'+target).then(setSchedule).catch(e=>setError(e.message));if(source)api('/settings/'+target).then(setSettings).catch(e=>setError(e.message))},[target]);
  return <><div className="page-heading"><div><span className="eyebrow">ADMINISTRATION</span><h1>Settings<span className="heading-dot">.</span></h1><p>Control when work happens. Changes apply between worker cycles.</p></div></div><div className="settings-layout"><div className="settings-nav"><small>SOURCE WORKERS</small>{['nvd','cve'].map(s=><button className={target===s?'active':''} key={s} onClick={()=>onSelect(s)}>{s.toUpperCase()} synchronization</button>)}<small>PROJECT SCHEDULES</small>{projects.map(p=><button className={target==='project:'+p.id?'active':''} key={p.id} onClick={()=>onSelect('project:'+p.id)}>{p.company} — {p.name}</button>)}</div><div className="settings-content">{error&&<div className="alert">{error}</div>}{!schedulable&&<div className="panel"><h2>{target}</h2><p>{target==='report-worker'?'One report executes at a time. Jobs run against current local data and automatically export their results.':target==='queue'?'Project schedules and Run now requests feed the durable report queue. Each project can have one queued or active job.':target==='database'?'Shared PostgreSQL storage contains compact NVD/CVE intelligence, project metadata, and report history.':target==='storage'?'The newest 30 successful reports are retained per project. Uploaded SBOM versions remain available.':'The scheduler checks enabled project schedules every two seconds.'}</p><p>Use the project schedule controls to configure report generation.</p></div>}
  {schedule&&<form className="panel" onSubmit={e=>{e.preventDefault();act(async()=>{const {enabled,mode,expression,timezone,interval_seconds}=schedule;setSchedule(await api('/schedules/'+target,'PUT',{enabled,mode,expression,timezone,interval_seconds:Number(interval_seconds)}))},'Schedule saved')}}><div className="section-bar"><h2>{source?target.toUpperCase()+' synchronization':'Scan & export schedule'}</h2><Badge state={schedule.enabled?'enabled':'paused'}/></div><Field label="Scheduling"><select value={String(schedule.enabled)} onChange={e=>setSchedule({...schedule,enabled:e.target.value==='true'})}><option value="false">Paused</option><option value="true">Enabled</option></select></Field>{source&&<Field label="Schedule type"><select value={schedule.mode} onChange={e=>setSchedule({...schedule,mode:e.target.value})}><option value="interval">Repeating interval</option><option value="cron">Cron schedule</option></select></Field>}{schedule.mode==='interval'?<Field label="Interval in seconds"><input type="number" min={60} value={schedule.interval_seconds} onChange={e=>setSchedule({...schedule,interval_seconds:e.target.value})}/></Field>:<Field label="Cron expression · minute hour day month weekday"><input value={schedule.expression} onChange={e=>setSchedule({...schedule,expression:e.target.value})} placeholder="0 7 * * *"/><small>Example: 0 7 * * * runs daily at 07:00.</small></Field>}<Field label="Timezone"><input value={schedule.timezone} onChange={e=>setSchedule({...schedule,timezone:e.target.value})}/></Field><p>Scheduled time queues the job. Actual start depends on available capacity. Reports use local data even if a source is stale.</p><button disabled={busy} className="primary">Save schedule</button><div className="upcoming"><small>NEXT FIVE OCCURRENCES · SAVED CONFIGURATION</small>{schedule.upcoming?.map((d:string)=><div key={d}>{inZone(d,schedule.timezone)} <span>{schedule.timezone}</span></div>)}</div></form>}
  {settings&&<form className="panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const values=Object.fromEntries(f);if(!values.api_key)delete values.api_key;act(async()=>setSettings(await api('/settings/'+target,'PUT',values)),'Worker settings saved')} }><div className="section-bar"><h2>Worker configuration</h2><small>Saved v{settings.version}</small></div><div className="form-grid">{Object.entries(settings.settings).filter(([k])=>target==='nvd'||!k.includes('pause')).map(([k,v])=><Field key={target+k+settings.version} label={k.replaceAll('_',' ')}><input name={k} defaultValue={String(v||'2s')} required/></Field>)}</div>{target==='nvd'&&<Field label={'NVD API key · '+(settings.has_api_key?'configured':'not configured')}><input name="api_key" type="password" autoComplete="new-password" placeholder="Leave blank to keep existing key"/></Field>}<div className="button-row"><button disabled={busy} className="primary">Save worker settings</button>{target==='nvd'&&settings.has_api_key&&<button type="button" disabled={busy} onClick={()=>act(async()=>setSettings(await api('/settings/'+target,'PUT',{...settings.settings,api_key:''})),'API key cleared')}>Clear API key</button>}</div></form>}</div></div></>
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
