import { test, expect } from '@playwright/test';

test('project upload, report execution, HTML, settings and deletion',async({page})=>{
  test.setTimeout(60000);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Sign in to CVEX'})).toBeVisible();
  await page.screenshot({path:'test-results/login.png',fullPage:true});
  await page.getByLabel('Username',{exact:true}).fill('browser-admin');
  await page.getByLabel('Password',{exact:true}).fill('browser-test-password');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.getByRole('button',{name:'New project'}).click();
  await page.getByLabel('Company',{exact:true}).fill('Orion Systems');
  const name='Gateway firmware '+Date.now();
  await page.getByLabel('Project / SBOM name').fill(name);
  await page.getByRole('button',{name:'Create project',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Orion Systems — '+name})).toBeVisible();
  await page.getByLabel('Version label').fill('2.4.0');
  await page.getByLabel('SPDX JSON file').setInputFiles({name:'gateway.spdx.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({spdxVersion:'SPDX-2.3',name,packages:[{SPDXID:'SPDXRef-curl',name:'curl',versionInfo:'8.0.1'}]}))});
  await page.getByRole('button',{name:'Upload SPDX JSON'}).click();
  await expect(page.getByText('SBOM uploaded',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Run now',exact:true}).click();
  await expect(page.getByRole('link',{name:'View HTML'})).toBeVisible({timeout:60000});
  const reportPath=await page.getByRole('link',{name:'View HTML'}).getAttribute('href');
  const popup=page.waitForEvent('popup');await page.getByRole('link',{name:'View HTML'}).click();
  const report=await popup;await report.waitForLoadState();await expect(report.locator('body')).toContainText('Orion Systems');await expect(report.locator('body')).toContainText(name);await report.close();
  await page.bringToFront();
  const downloaded=page.waitForEvent('download');await page.getByRole('link',{name:'Download HTML'}).click();
  expect((await downloaded).suggestedFilename()).toBe('findings.html');
  await page.screenshot({path:'test-results/project.png',fullPage:true});
  await page.getByRole('button',{name:'Schedule',exact:true}).click();
  await page.getByLabel('Cron expression').fill('15 6 * * *');
  await page.getByRole('button',{name:'Save schedule'}).click();
  await expect(page.getByText('Schedule saved',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Architecture',exact:true}).click();
  await expect(page.getByText('PostgreSQL intelligence')).toBeVisible();
  await page.screenshot({path:'test-results/architecture.png',fullPage:true});
  await page.getByText('NVD synchronization',{exact:true}).click();
  await expect(page.getByRole('heading',{name:'Worker configuration'})).toBeVisible();
  await page.getByRole('button',{name:'Save worker settings'}).click();
  await expect(page.getByText('Worker settings saved',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:/^Projects\b/}).click();
  await expect(page.getByRole('heading',{name:'Orion Systems — '+name})).toBeVisible();
  await page.getByRole('button',{name:'Delete project',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'Delete permanently',exact:true}).click();
  await expect(page.getByText('Project deleted permanently',{exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:new RegExp(name)})).toHaveCount(0);
  expect((await page.request.get(reportPath!)).status()).toBe(404);
  expect(errors).toEqual([]);
});
